stages:
  - code-style

phpcs-magento2:
  image: domw/phpcs
  type: code-style
  tags:
    - docker
  script:
    - phpcs --version
    - phpcs -i
    - phpcs --colors --standard=Magento2 --warning-severity=0 --report=full,summary,gitblame /builds/magento-modules/m2-banner-manager/
