stages:
  - code-style
  - php-stan

phpcs-magento2:
  image: domw/phpcs
  type: code-style
  tags:
    - docker
  script:
    - phpcs --version
    - phpcs -i
    - phpcs --colors --standard=Magento2 --report=full,summary,gitblame /builds/magento-modules/m2-banner-manager/

php-stan:
  image: domw/phpstan:gitlab-7.3
  type: php-stan
  tags:
    - docker
  script:
    - composer global config http-basic.repo.magento.com d2eb3c98428210463077e4ca2b806e90 bf5d07ecb44854e94d7f78ef969d9470
    - composer install --prefer-dist -o --no-dev --ignore-platform-reqs -d /builds/magento-modules/m2-banner-manager
    - phpstan --version
    - phpstan analyze --level 0 /builds/magento-modules/m2-banner-manager/
