dist: trusty

language: php

sudo: false

php:
    - 5.6
    - 7.0

env:
    global:
        - secure: "CLyHxMKB8L1P8A+xIJHIAqYwwsmKE/ipOJXVgnKpLBQa9auLARtwC9HC/+Dd67RuKyn/bZ/NulfWmKNDqFPmK/qfFGkN5Z1Q+/WPCmGbdRtCTdwcWSVvvmlLFBfLCpVavX446dEavHh9TjGI79M8wC1C7TkHqfIUPuRyR8KHJoSJr+HgflEe3IYqVyQJyWVkEhWyezip9S3j+2Tj2hOt8tSphKyhzsUkBI2dFYC3sstiKF0fPJ0EHpgVsxauj4569kQQaLaqqyoSLzJMHHUYEnujcc5H4+qvraVrjblMCrXr/5AKtHVS8Ou4CtcxpKg8HK+yWrG3hDrnXh0Thy1qNIsVcNBI6ca32fyWtzmn10BeCDWqjXhDOxlnoC4U5h2Y8lrvaHKVSCwp7iV7cFJtfwemmp1XfcnfPkw+NY9CYheka+8JHZvZPxuAh17EOVzsM/VB9NxH9bC+y8tHRUoKqsNKe2SmRLm3ZX9cza3hiC1XxxwqywaG3vHclUi2rg87dKrNMwYWx6uiWKpe8GqjUc3Xhuplb5NuWYe9cPU0FUh/OwxAcIwEOKPF/cf+gTTUN59H0qSu2Y/xn89rSPf+69gt0KuAKOPHnHRaYhlDO/OZZMq9FwNdPN4X7gjJBnGmujO4ElD6t0WlqKwHjHzhNafoFFDmaUZ6VywKu/15+/w="
        - secure: "kQ3f6XNfL4P4cWw6VcZ09ORFsqZcmeEkVPx5Fsb1rQ+5eW4zMoFgzI9OAWMlzKY9SbwbaInMwKusYZVeDJL/kSxgWk38UFIn+K9sRjVURIqfnXhLKQlob4FaBeGBo8b1Odi10MuIhhq2rQkHPewEf0cG4bg80ZmIj6ZrOdxzlbNxhmOhBWWj6WepONtRAuzq6uEeMKcvZ7P2FjtIfA9yTChimlOSxAaaNsnF6IRbeA9h1axarw1flla2pB0YeJfmKBEdcX2L5BkR7eEKfe/uIDkdlfjU4bz/pdJxsg/ztgrwT6OfPSx9D/OiuCJJOn2zpAXXzYxaAgaPWbd96F73Myo/VDEG43W/2UcUclskzs2T3usn0WVbeccj8nxVF3aEtwWleWt4nT8P3Wvh+0d8KE/sT7CyIBWl2y1zDzKzNarb4A5MZ4HIr08WMLdxf5fI5n448Ck6AWPWsui3mue8n1/XthQRNQepqlgZ2KTBRU3mbPaFzqCGv8/OisGeIQ86CdvxVaueXRscgKAaN3ywOVb/bM6zvS/dvHQ/LYTgUZJ1U8o7wLaUw+eKlBjUQzWdXalEiLI197yeWOVNCkXjgB73BhqknOiw7qzp36AX0BD/tckaoSvUPoQAMqiD39YZxMZ9OCHIGKtK1Il3ZowqCo95bGscMuj2nJzueCuhv7A="
    matrix:
        - TEST_SUITE=unit

matrix:
    exclude:
        - php: 7.0

cache:
    directories:
        - $HOME/.composer/cache

install:
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then echo '{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}' > auth.json; fi"
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then composer install --prefer-dist; fi"

script:
#    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/phpdoc run -d Block,Helper,Model,Observer -t build/doc; fi"
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/phpcs Block --standard=psr2 --warning-severity=0; fi"
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/phpcs Controller --standard=psr2 --warning-severity=0; fi"
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/phpcs Helper --standard=psr2 --warning-severity=0; fi"
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/phpcs Model --standard=psr2 --warning-severity=0; fi"
#    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/phpmd Block/,Helper/,Model/,Observer/,Test/ text cleancode,codesize,controversial,design,naming,unusedcode; fi"
#    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/phpcpd Block/ Helper/ Model/ Observer/ Test/; fi"
