<?php
/**
 * @author Xigen
 */
?>
<div class="carousel-wrapper">
    <div class="container">
        <div class="row">
            <div id="homepage-carousel" class="carousel slide hidden-xs col-xs-lip" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                <?php $i = 0; foreach ($block->getBannerCollection() as $banner) :
                    ?> <li data-target="#homepage-carousel" data-slide-to="<?= $i; ?>" class="<?= (($i == 0) ? 'active' : '');?>"></li><?php $i++;

                endforeach; ?>
                </ol>
                <!-- Wrapper for slides -->
                <div class="carousel-inner"><?php $i = 0;
                foreach ($block->getBannerCollection() as $banner) :
                    $i++; ?>                  
                    <div class="item <?= (($i == 1) ? 'active' : '');?>">
                        <?php if ($banner->getClickUrl()) :
                            ?><a href="<?= $banner->getClickUrl(); ?>" target="<?= $banner->getTargetValue() ?>"><?php
                        endif; ?>
                        <img src="<?= $block->getBannerImageUrl($banner) ?>" title="<?= $banner->getName(); ?>" alt="<?= $banner->getName(); ?>" />
                        <div class="carousel-caption">
                            <?php if ($banner->getShowTitle() == 1 && $banner->getName()) : ?>
                            <h3><?= $banner->getName(); ?></h3>
                            <?php endif; ?>
                            <?php if (!empty($banner->getCaption())) : ?>
                            <p><?= $banner->getCaption(); ?></p>
                            <?php endif; ?>
                        </div>
                        <?php if ($banner->getClickUrl()) :
                            ?></a><?php
                        endif; ?>
                <?php endforeach; ?>    
                </div>
                <!-- Controls -->
                <a class="left carousel-control" href="#homepage-carousel" data-slide="prev">
                    <i class="fa arrows fa-chevron-left"></i>
                </a>
                <a class="right carousel-control" href="#homepage-carousel" data-slide="next">
                    <i class="fa arrows fa-chevron-right"></i>
                </a>
            </div>
        </div>
    </div><!-- /.container -->
</div><!-- /.carousel-wrapper -->