<?php
/**
 * @author Xigen
 */
// phpcs:disable Magento2.Files.LineLength.MaxExceeded
// phpcs:disable Squiz.WhiteSpace
?>
<div class="carousel-wrapper">
    <div class="container">
        <div class="row">
            <div id="homepage-carousel" class="carousel slide hidden-xs col-xs-lip" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                <?php $i = 0; foreach ($block->getBannerCollection() as $banner): ?> 
                    <li data-target="#homepage-carousel" 
                        data-slide-to="<?= $block->escapeHtmlAttr($i); ?>" 
                        class="<?= (($i == 0) ? 'active' : '');?>"></li>
                <?php $i++; endforeach; // phpcs:ignore ?>
                </ol>
                <!-- Wrapper for slides -->
                <div class="carousel-inner">
                    <?php $i = 0; foreach ($block->getBannerCollection() as $banner) : $i++; // phpcs:ignore ?>
                    <div class="item <?= (($i == 1) ? 'active' : '');?>">
                        <?php if ($banner->getClickUrl()): ?>
                        <a href="<?= /* @noEscape */ $banner->getClickUrl(); ?>" 
                           target="<?= $block->escapeHtmlAttr($banner->getTargetValue()) ?>">
                        <?php endif; ?>
                        <img src="<?= /* @noEscape */ $block->getBannerImageUrl($banner) ?>" 
                             title="<?= $block->escapeHtmlAttr($banner->getName()); ?>" 
                             alt="<?= $block->escapeHtmlAttr($banner->getName()); ?>" />
                        <div class="carousel-caption">
                            <?php if ($banner->getShowTitle() == 1 && $banner->getName()): ?>
                            <h3><?= $block->escapeHtml($banner->getName()); ?></h3>
                            <?php endif; ?>
                            <?php if (!empty($banner->getCaption())): ?>
                            <p><?= $block->escapeHtml($banner->getCaption()); ?></p>
                            <?php endif; ?>
                        </div>
                        <?php if ($banner->getClickUrl()): ?>
                        </a>
                        <?php endif; ?>
                    </div>
                    <?php endforeach; ?>    
                </div>
                <!-- Controls -->
                <a class="left carousel-control" href="#homepage-carousel" data-slide="prev">
                    <i class="fa arrows fa-chevron-left"></i>
                </a>
                <a class="right carousel-control" href="#homepage-carousel" data-slide="next">
                    <i class="fa arrows fa-chevron-right"></i>
                </a>
            </div>
        </div>
    </div><!-- /.container -->
</div><!-- /.carousel-wrapper -->