<?php
/**
 * bannermanager slider template
 * @author Xigen
 */
?>
<div id="homepage-carousel-<?= $block->getSlider()->getId(); ?>">
    <div class="hero-slider <?= $block->getSlider()->getCssClass(); ?>">
        <?php $i = 0;
        foreach ($block->getBannerCollection() as $banner) :
            $i++; ?>
        <div class="slide <?= (($i == 1) ? 'active' : '');?>" data-id="<?= $banner->getId(); ?>">
            <?php if ($banner->getClickUrl()) :
                ?><a href="<?= $banner->getClickUrl(); ?>" target="<?= $banner->getTargetValue() ?>"><?php
            endif; ?>
            <img src="<?= $block->getBannerImageUrl($banner) ?>" title="<?= $banner->getName(); ?>" alt="<?= $banner->getName(); ?>" class="img-responsive" />
            <div class="carousel-caption">
                <?php if ($banner->getShowTitle() == 1 && $banner->getName()) : ?>
                <h3><?= $banner->getName(); ?></h3>
                <?php endif; ?>
                <?php if (!empty($banner->getCaption())) : ?>
                    <?= $banner->getCaption(); ?>
                <?php endif; ?>
            </div>
            <?php if ($banner->getClickUrl()) :
                ?></a><?php
            endif; ?>
        </div>
        <?php endforeach; ?>
    </div>
</div>

<script>
require(["jquery", "slick.slider"], function($) {
    $(".hero-slider").slick({
        autoplay: true,
        autoplaySpeed: 5000,
        dots: false,
        arrows: false,
        infinite: true,
        slidesToShow: 1,
        slidesToScroll: 1,
        fade: true,
    });
});
</script>
