<?php

/**
 * bannermanager slider template
 * @author Xigen
 */
// phpcs:disable

// two banners simultanious sends query logic haywire
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$resource       = $objectManager->get(\Magento\Framework\App\ResourceConnection::class);
$connection     = $resource->getConnection();
$xbb            = $resource->getTableName('xigen_bannermanager_banner');
$order          = $block->getSlider()->getSortType() == \Xigen\Bannermanager\Model\Slider::SORT_TYPE_RANDOM ? 'RAND()' : 'order_banner';
$banners = $connection->fetchAll("SELECT * FROM " . $xbb . " 
                                  WHERE status = " . $connection->quote(\Xigen\Bannermanager\Model\Status::STATUS_ENABLED)  . " 
                                  AND slider_id = " .  $connection->quote($block->getSlider()->getId()) . " 
                                  ORDER BY $order ASC ");
?>
<?php if ($banners): ?>
    <?php if ($block->isShowTitle() == 1): ?>
        <div class="xigen-bannermanager-static-title">
            <strong><span><?= $block->escapeHtml($block->getSlider()->getTitle()); ?></span></strong>
        </div>
    <?php endif; ?>
    <div class="xigen-bannermanager-static" id="static-slider-<?= $block->escapeHtmlAttr($block->getSlider()->getId()); ?>">
            <?php $i = 0;
            foreach ($banners as $loadbanner):
                $i++; ?>
                <?php
                // literally wasted hours on simplest feature
                $banner = $objectManager->get(\Xigen\Bannermanager\Model\BannerFactory::class)->create();
                $banner->load($loadbanner['banner_id']);
                ?>
                <div>
                    <?php if ($banner->getClickUrl()): ?>
                    <a href="<?= /* @noEscape */$banner->getClickUrl() ?>" target="<?= /* @noEscape */ $banner->getTargetValue() ?>">
                    <?php endif; ?>
                        <img alt="<?= $block->escapeHtmlAttr(($banner->getImageAlt()) ? $banner->getImageAlt() :  $banner->getName()); ?>" 
                             title="<?= $block->escapeHtmlAttr(($banner->getImageAlt()) ? $banner->getImageAlt() :  $banner->getName()); ?>"  
                             src="<?= /* @noEscape */ $block->getBannerImageUrl($banner) ?>" 
                             class="img-responsive"/>
                    <?php if ($banner->getClickUrl()): ?>
                    </a>
                    <?php endif; ?>
                                
                    <?php if ($banner->getShowTitle() == 1 && $banner->getName()): ?>
                    <h2><?= $block->escapeHtml($banner->getName()) ?></h2>
                    <?php endif; ?>
                    
                    <?php if ($banner->getCaption()): ?>
                    <p><?= $block->escapeHtml(strip_tags($banner->getCaption())) ?></p>
                    <?php endif; ?>
                </div>
            <?php endforeach ?>
    </div>

<?php endif; ?>