<?php
/**
 * Xigen
 */
// phpcs:disable
?>
<?php if ($block->isShowTitle() == 1): ?>
    <div class="xigen-bannermanager-title"
         style="font: bold 12px/16px Arial, Helvetica, sans-serif;text-transform: uppercase;color: #e26703;">
        <strong><span><?= $block->escapeHtml($block->getSlider()->getTitle()); ?></span></strong>
    </div>
<?php endif; ?>
<div class="xigen-bannermanager-static">
    <?php foreach ($block->getBannerCollection() as $banner): ?>
        <div>
            <?php if ($banner->getClickUrl()): ?>
            <a href="<?= /* @noEscape */ $banner->getClickUrl() ?>" target="<?= /* @noEscape */ $banner->getTargetValue() ?>">
            <?php endif; ?>
                <img alt="<?= $block->escapeHtmlAttr(($banner->getImageAlt()) ? $banner->getImageAlt() :  $banner->getName()); ?>" 
                     title="<?= $block->escapeHtmlAttr(($banner->getImageAlt()) ? $banner->getImageAlt() :  $banner->getName()); ?>"  
                     src="<?= /* @noEscape */ $block->getBannerImageUrl($banner) ?>" 
                     class="img-responsive"/>
            <?php if ($banner->getClickUrl()): ?>
            </a>
            <?php endif; ?>
            <?php if ($banner->getShowTitle() == 1 && $banner->getName()): ?>
            <h2><?= $block->escapeHtml($banner->getName()) ?></h2>
            <?php endif; ?>
            
            <?php if ($banner->getCaption()): ?>
            <p><?= $block->escapeHtml(strip_tags($banner->getCaption())) ?></p>
            <?php endif; ?>
            
        </div>
    <?php endforeach ?>
</div>
